//ordersPage
export const CLICK_ALL_CHECKED_ORDERS = 'CLICK_ALL_CHECKED_ORDERS';
export const CLICK_CHECKED_ORDER = 'CLICK_CHECKED_ORDER';
export const SELECT_ARROW_OPTION_ORDER = 'SELECT_ARROW_OPTION_ORDER';
export const CHANGE_STATUS_ORDER = 'CHANGE_STATUS_ORDER';
export const CHANGE_BTN_STATUS_ORDER = 'CHANGE_BTN_STATUS_ORDER';

//productsPage
export const CLICK_ALL_CHECKED_PRODUCTS = 'CLICK_ALL_CHECKED_PRODUCTS';
export const CLICK_CHECKED_PRODUCT = 'CLICK_CHECKED_PRODUCT';
export const SELECT_ARROW_OPTION_PRODUCTS = 'SELECT_ARROW_OPTION_PRODUCTS';
export const CHANGE_STATUS_PRODUCTS = 'CHANGE_STATUS_PRODUCTS';
export const CHANGE_BTN_STATUS_PRODUCT = 'CHANGE_BTN_STATUS_PRODUCT';
export const CLICK_ADD_NEW_PRODUCT = 'CLICK_ADD_NEW_PRODUCT';

//ui
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

